site_name: Edgy Guardian
site_description: Permission system for your models with Edgy.
site_url: https://edgy-guardian.dymmond.com

theme:
  name: "material"
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: "default"
      primary: "pink"
      accent: "red"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "pink"
      accent: "red"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  favicon: statics/images/favicon.ico
  logo: statics/images/logo-white.svg
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.code.select
    - navigation.indexes
    - navigation.path
    - navigation.tabs

repo_name: dymmond/edgy-guardian
repo_url: https://github.com/dymmond/edgy-guardian
edit_uri: ""
plugins:
  - search
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            preload_modules: [databasez]
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - Introduction: "index.md"
  - Mixin: "mixins.md"
  - Shortcuts: "shortcuts.md"
  - Contributing: "contributing.md"
  - Sponsorship: "sponsorship.md"
  - Release Notes: "release-notes.md"

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - mdx_include:
      base_path: docs
  - admonition
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
extra:
  alternate:
    - link: /
      name: English
      lang: en
