version: 3

env:
  ESMERALD_SETTINGS_MODULE: guardian.configs.settings.AppSettings
  EDGY_SETTINGS_MODULE: guardian.configs.edgy.EdgyAppSettings
  EDGY_DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/guardian

tasks:
  # --------------------------- SETUP ------------------------------------

  activate:
    desc: Activates the virtual environment in development mode
    cmds:
      - hatch shell

  clean:
    desc: Cleans caching, pyc and pycache files
    cmds:
      - hatch run clean_pyc
      - hatch run clean_pyi
      - hatch run clean_pycache

  build_with_checks:
    desc: Builds the project with checks
    cmds:
      - hatch run build_with_check

  lint:
    desc: Lints the project
    cmds:
      - hatch run lint

  format:
    desc: Formats the project
    cmds:
      - hatch run format

  mypy:
    desc: Runs the type checker only, no formatting
    cmds:
      - hatch run test:check_types

  #---------------------------- DOCS -------------------------------

  build:
    desc: Builds the documentation
    cmds:
      - hatch run docs:build

  serve:
    desc: Runs the documentation in live mode
    cmds:
      - hatch run docs:serve

  # --------------------------- TEST ------------------------------------

  test:
    desc: Runs the suite tests
    dir: "tests/guardian"
    cmds:
      - ESMERALD_SETTINGS_MODULE=guardian.configs.testing.settings.TestingAppSettings pytest {{.TESTONLY}} -s --disable-warnings

  test_man:
    desc: Runs the suite tests for specific modules
    dir: "tests/guardian"
    cmds:
      - ESMERALD_SETTINGS_MODULE=guardian.configs.testing.settings.TestingAppSettings hatch run test:test_man {{ .TESTONLY}}

  coverage:
    desc: Runs the coverage tests
    dir: "tests/guardian"
    cmds:
      - hatch run test:coverage {{ .ARGS }}
