version: 3

tasks:
  # --------------------------- SETUP ------------------------------------

  activate:
    desc: Activates the virtual environment in development mode
    cmds:
      - hatch shell

  clean:
    desc: Cleans caching, pyc and pycache files
    cmds:
      - hatch run clean_pyc
      - hatch run clean_pyi
      - hatch run clean_pycache

  build_with_checks:
    desc: Builds the project with checks
    cmds:
      - hatch run build_with_check

  lint:
    desc: Lints the project
    cmds:
      - hatch run lint

  mypy:
    desc: Runs the type checker only, no formatting
    cmds:
      - hatch run test:check_types

  format:
    desc: Formats the project
    cmds:
      - task mypy

  #---------------------------- DOCS -------------------------------

  build:
    desc: Builds the documentation
    cmds:
      - hatch run docs:build

  serve:
    desc: Runs the documentation in live mode
    cmds:
      - hatch run docs:serve

  # --------------------------- TEST ------------------------------------

  test:
    desc: Runs the suite tests
    cmds:
      - hatch run test:test {{ .CLI_ARGS}}

  test_man:
    desc: Runs the suite tests for specific modules
    cmds:
      - hatch run test:test_man {{ .CLI_ARGS}}

  coverage:
    desc: Runs the coverage tests
    cmds:
      - hatch run test:coverage {{ .CLI_ARGS }}
