"""
Esmerald settings for bandore project.

Generated by 'esmerald createproject' using Esmerald 3.6.0
"""

from functools import cached_property
from typing import Optional

from edgy import Registry
from edgy.testclient import DatabaseTestClient
from esmerald.conf.enums import EnvironmentType

from ..settings import AppSettings


class TestingAppSettings(AppSettings):
    debug: bool = True
    environment: Optional[str] = EnvironmentType.TESTING

    @cached_property
    def database(self) -> DatabaseTestClient:
        return DatabaseTestClient(url=self.db_url)

    @cached_property
    def registry(self) -> Registry:
        return Registry(database=self.database)
