#!/usr/bin/env python
"""
Generated by 'esmerald createproject' using Esmerald 3.6.7.
"""

import os
import sys

from esmerald import Esmerald

from edgy_guardian.loader import handle_content_types


def build_path():
    """
    Builds the path of the project and project root.
    """
    SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

    if SITE_ROOT not in sys.path:
        sys.path.append(SITE_ROOT)
        sys.path.append(os.path.join(SITE_ROOT, "apps"))


def get_application():
    """
    This is optional. The function is only used for organisation purposes.
    """
    build_path()
    from edgy import Instance, monkay
    from edgy.conf import settings as edgy_settings
    from esmerald.conf import settings

    # Initialise the registry and pass it to `edgy_guardian`.
    edgy_settings.edgy_guardian.register(settings.registry)

    # ensure the settings are loaded
    monkay.evaluate_settings(
        ignore_preload_import_errors=False,
        onetime=False,
    )

    app = Esmerald(
        on_startup=[
            settings.registry.__aenter__,
            handle_content_types,
        ],
        on_shutdown=[settings.registry.__aexit__],
    )
    monkay.set_instance(Instance(registry=app.settings.registry, app=app))
    return app


app = get_application()
