"""
Esmerald settings for guardian project.

Generated by 'esmerald createproject' using Esmerald 3.6.7.
"""

from functools import cached_property
from typing import Optional

from edgy import Registry
from edgy.testclient import DatabaseTestClient
from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings
from lilya.environments import EnvironLoader

loader = EnvironLoader()


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    title: str = "My guardian"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = (
        "esmerald-insecure-g1djt(xzn1fa6#^y8jrqs=rocw)nze1j6aoqo&amp;0x&amp;*^421d_7q"
    )

    @cached_property
    def db_url(self) -> str:
        return loader(
            "EDGY_DATABASE_URL",
            cast=str,
            default="postgresql+asyncpg://postgres:postgres@localhost:5432/guardian",
        )

    @cached_property
    def database(self) -> DatabaseTestClient:
        return DatabaseTestClient(self.db_url)

    @cached_property
    def registry(self) -> Registry:
        return Registry(self.database)
